# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import asyncio
from logging import critical
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox
import sys
import shutil
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(300, 152)
        MainWindow.setMaximumSize(QtCore.QSize(300, 152))
        MainWindow.setSizeIncrement(QtCore.QSize(300, 152))
        MainWindow.setTabletTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:#19032e;\n"
"    position: fixed;\n"
"    \n"
"}\n"
"QPushButton{\n"
"    border-radius: 30px;\n"
"    font-size: 12px;\n"
"    background-color: #f2f2fa;\n"
"    border-radius: 12px;;\n"
"    font-weight: 700;\n"
"    font-family: monospace;\n"
"    position: flex;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #c0c0d1;\n"
"    border-radius: 12px;\n"
"    font-weight: 700;\n"
"    font-family: monospace;\n"
"}    \n"
"QPushButton:pressed{\n"
"    background-color: #87879c;\n"
"    border-radius: 12px;\n"
"    font-weight: 700;\n"
"    font-family: monospace;\n"
"}")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNoEditMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 50, 191, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Destroy temporary files"))
        self.pushButton.setText(_translate("MainWindow", "DELETE"))

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
      
    
pather = os.chdir("C:/Users/topyt/AppData/Local/Temp/")
path = os.getcwd()
def delete():
    print(path)
    for i in os.listdir(path):
        try:
            shutil.rmtree(i)
        except Exception as ex:
            print(ex)
            continue
    ui.pushButton.setText("Success!")


ui.pushButton.clicked.connect(delete)

    
sys.exit(app.exec_())   